# Generated by Django 5.2.14 on 2026-05-28 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tier', models.CharField(choices=[('metro', 'Metro'), ('tier_1', 'Tier 1'), ('tier_2', 'Tier 2'), ('tier_3', 'Tier 3'), ('semi_urban', 'Semi-Urban'), ('rural', 'Rural')], default='tier_2', max_length=20)),
                ('fuel_price', models.FloatField(default=90.0)),
                ('congestion_index', models.FloatField(default=0.5, help_text='0.0 to 1.0')),
                ('avg_intra_city_speed', models.FloatField(default=25.0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('discount_percentage', models.FloatField(default=0.0)),
                ('platform_fee_percentage', models.FloatField(default=5.0)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('multiplier', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='ValueAddedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('fuel_efficiency_kmpl', models.FloatField(help_text='KM per litre of diesel')),
                ('toll_rate_per_km', models.FloatField()),
                ('capacity_tons', models.FloatField()),
                ('capacity_cbm', models.FloatField()),
                ('depreciation_annual', models.FloatField(default=0)),
                ('insurance_annual', models.FloatField(default=0)),
                ('driver_salary_annual', models.FloatField(default=0)),
                ('permit_fees_annual', models.FloatField(default=0)),
                ('maintenance_per_km', models.FloatField(default=0)),
                ('tire_cost_per_km', models.FloatField(default=0)),
                ('estimated_annual_km', models.FloatField(default=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PricingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(max_length=20, unique=True)),
                ('origin_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('cargo_weight_tons', models.FloatField()),
                ('cargo_volume_cbm', models.FloatField()),
                ('final_total', models.FloatField()),
                ('breakdown', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customersegment')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servicetier')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('terrain_grade', models.FloatField(default=1.0)),
                ('road_surface_quality', models.FloatField(default=1.0)),
                ('traffic_congestion', models.FloatField(default=1.0)),
                ('weather_risk', models.FloatField(default=1.0)),
                ('toll_gate_density', models.FloatField(default=1.0)),
                ('historical_accident_rate', models.FloatField(default=1.0)),
                ('border_checkpoint_freq', models.FloatField(default=1.0)),
                ('lane_viability', models.CharField(choices=[('highly_balanced', 'Highly Balanced'), ('moderately_balanced', 'Moderately Balanced'), ('unbalanced_origin_heavy', 'Unbalanced (Origin Heavy)'), ('seasonal', 'Seasonal'), ('remote_low_demand', 'Remote / Low Demand')], default='moderately_balanced', max_length=30)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='core.city')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='core.city')),
            ],
            options={
                'unique_together': {('origin', 'destination')},
            },
        ),
    ]
