# Generated by Django 5.2.14 on 2026-05-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='fuel_price',
            field=models.DecimalField(decimal_places=2, default=90.0, max_digits=10),
        ),
    ]
